### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ShrutiKaha** [IntelLabs/coach#473]
I am using Anaconda on Windows 10. On running the first example code. (base) C:\Users\shrut>coach -p Atari_DQN -lvl breakout
The following error occurs: 

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\shrut\AppData\Roaming\Python\Python38\Scripts\coach.exe\__main__.py", line 4, in <module>
  File "C:\Users\shrut\AppData\Roaming\Python\Python38\site-packages\rl_coach\coach.py", line 39, in <module>
    from rl_coach.graph_managers.graph_manager import HumanPlayScheduleParameters, GraphManager
  File "C:\Users\shrut\AppData\Roaming\Python\Python38\site-packages\rl_coach\graph_managers\graph_manager.py", line 35, in <module>
    from rl_coach.data_stores.data_store_impl import get_data_store as data_store_creator
  File "C:\Users\shrut\AppData\Roaming\Python\Python38\site-packages\rl_coach\data_stores\data_store_impl.py", line 19, in <module>
    from rl_coach.data_stores.s3_data_store import S3DataStore, S3DataStoreParameters
  File "C:\Users\shrut\AppData\Roaming\Python\Python38\site-packages\rl_coach\data_stores\s3_data_store.py", line 20, in <module>
    from minio.error import ResponseError
ImportError: cannot import name 'ResponseError' from 'minio.error' (C:\Users\shrut\AppData\Roaming\Python\Python38\site-packages\minio\error.py)

I think its because there is no 'ResponseError' but 'InvalidResponseError' in the python file. What to do?

**Comment by RundownRhino** [comment]
I was able to fix this particular problem by downgrading minio to 6.0.0 (haven't checked whether that's the lowest version that fixes it, but `coach` only requires `minio>=4.0.5`.

**Comment by alecacco** [comment]
Can confirm this is an issue, I just had it myself. Manually downgraded to minio==4.0.5 in my venv and it worked. Still, not ideal, to say the least

**Comment by MattPat1981** [comment]
I manually downgraded to minio==4.0.5 and I am still getting this same error message
